### PR TITLE
Added word2vec-doc2vec tool support (https://github.com/nliu86/word2vec-doc2vec)

### PR DESCRIPTION
**Pull request by artiz**
Hi, I am playing witsh doc2vec on Windows and found your repo. Thanks for big job!
But I found that doc2vec tool is not availbale here, so I decided to introduce it.
Having this fix doc2vec demo (http://nbviewer.jupyter.org/github/danielfrg/word2vec/blob/master/examples/doc2vec.ipynb) works fine with minimal installation

### CODE REVIEW

**Comment by zhangyafeikimi** [comment]
Hi, vcproj files are only file ending difference?  Would you keep the same file ending?

**Comment by artiz** [comment]
No, I just added new config folder for vs2015, still have no time to install 2017
So I had built/tested project only in vs2015 and decided not to update other configurations

**Comment by zhangyafeikimi** [comment]
Ok, right, please rebase to origin/master and upload patch again. I will merge it soom.

**Comment by zhangyafeikimi** [comment]
I will add vs2007 vcproj for you

**Comment by artiz** [comment]
It seems now it should be merged without any problem

**Pull request merged**
